spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.113.189.196:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  redis:
    host: 47.113.189.196
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  session:
    store-type: redis

# MapperScan
# sql映射文件位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 9999
logging:
  level:
    com.gy.gulimall.product: debug
feign:
  sentinel:
    enabled: true


#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'